# Base
site_name: UCL Research Computing Documentation
#site_url: https://wiki.rc.ucl.ac.uk/docs/
site_url: http://rits.github-pages.ucl.ac.uk/mkdocs-rc-docs/
site_author: UCL RCAS Team
site_description: Documentation for the centrally provided Research Computing HPC services at UCL.

# Halts site-build if broken internal links are found: disable in alpha
# strict: true

# Copyright
copyright: 'Copyright &copy; 2014 - 2018 UCL Research Computing Group'

# Associated Git Repo Config
repo_name: UCL-RITS/mkdocs-rc-docs
repo_url: https://github.com/UCL-RITS/mkdocs-rc-docs

# If this is removed, the edit buttons will go away. I like them.
edit_uri: blob/master/mkdocs-project-dir/docs/

# Theme Configuration
# Colour options: red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font: false
  logo: 'img/portico.svg'
#Boo GDPR
#  font:
#    text: 'Roboto'
#    code: 'Roboto Mono'
# To elaborate: when you specify fonts here, they are sourced from Google Fonts. This is an info leak.
# I'm not sure if this is a problem for GDPR-compliance, but strictly, removing the font spec here
#  makes it use the fonts UCL says we "should" anyway, so I guess it's an "improvement" either way.
  favicon: 'img/favicon.ico'

# Extensions
# NB: omitting linenums: setting means they get added when there's a shebang
# Even if it's a secret shebang -- shebangs with no forward-slash count but are removed
# See also: https://python-markdown.github.io/extensions/code_hilite/#usage
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      #linenums: true
  - toc:
      permalink: ยง

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/UCL-RITS'
