# Base
site_name: UCL Research Computing Documentation
#site_url: https://wiki.rc.ucl.ac.uk/docs/
site_author: UCL RCAS Team
site_description: Documentation for the centrally provided Research Computing HPC services at UCL.

# Copyright
copyright: 'Copyright &copy; 2014 - 2018 UCL Research Computing Group'

# Associated Git Repo Config
repo_name: UCL-RITS/mkdocs-rc-docs
repo_url: https://github.com/UCL-RITS/mkdocs-rc-docs
edit_uri: blob/master/mkdocs-project-dir/docs/

# Theme Configuration
# Colour options: red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'

# Extensions
# NB: omitting linenums: setting means they get added when there's a shebang
# Even if it's a secret shebang -- shebangs with no forward-slash count but are removed
# See also: https://python-markdown.github.io/extensions/code_hilite/#usage
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      #linenums: true
  - toc:
      permalink: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/UCL-RITS'
